# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := sel
### Rules for action "nacl_syscall_handler":
quiet_cmd_native_client_src_trusted_service_runtime_service_runtime_gyp_sel_target_nacl_syscall_handler = ACTION Creating nacl_syscall_handlers.c $@
cmd_native_client_src_trusted_service_runtime_service_runtime_gyp_sel_target_nacl_syscall_handler = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd native_client/src/trusted/service_runtime; mkdir -p $(obj).$(TOOLSET)/sel/geni; python nacl_syscall_handlers_gen.py -i posix/nacl_syscall_impl.c -o "$(obj).$(TOOLSET)/sel/geni/nacl_syscall_handlers.c"

$(obj).$(TOOLSET)/$(TARGET)/geni/nacl_syscall_handlers.c: obj := $(abs_obj)
$(obj).$(TOOLSET)/$(TARGET)/geni/nacl_syscall_handlers.c: builddir := $(abs_builddir)
$(obj).$(TOOLSET)/$(TARGET)/geni/nacl_syscall_handlers.c: TOOLSET := $(TOOLSET)
$(obj).$(TOOLSET)/$(TARGET)/geni/nacl_syscall_handlers.c: native_client/src/trusted/service_runtime/nacl_syscall_handlers_gen.py native_client/src/trusted/service_runtime/posix/nacl_syscall_impl.c FORCE_DO_CMD
	$(call do_cmd,native_client_src_trusted_service_runtime_service_runtime_gyp_sel_target_nacl_syscall_handler)

all_deps += $(obj).$(TOOLSET)/$(TARGET)/geni/nacl_syscall_handlers.c
action_native_client_src_trusted_service_runtime_service_runtime_gyp_sel_target_nacl_syscall_handler_outputs := $(obj).$(TOOLSET)/$(TARGET)/geni/nacl_syscall_handlers.c


DEFS_Debug := \
	'-DNACL_LINUX=1' \
	'-DNACL_ANDROID=0' \
	'-DNACL_OSX=0' \
	'-DNACL_WINDOWS=0' \
	'-D_BSD_SOURCE=1' \
	'-D_POSIX_C_SOURCE=199506' \
	'-D_XOPEN_SOURCE=600' \
	'-D_GNU_SOURCE=1' \
	'-D__STDC_LIMIT_MACROS=1' \
	'-D__STDC_FORMAT_MACROS' \
	'-DNACL_TARGET_SUBARCH=64' \
	'-DNACL_TARGET_ARCH=x86' \
	'-DNACL_BUILD_SUBARCH=64' \
	'-DNACL_BUILD_ARCH=x86' \
	'-D_DEBUG'

# Flags passed to all source files.
CFLAGS_Debug := \
	-Werror \
	-pthread \
	-fno-exceptions \
	-Wall \
	-fPIC \
	-Wextra \
	-Wno-long-long \
	-Wswitch-enum \
	-Wsign-compare \
	-Wundef \
	-fdiagnostics-show-option \
	-m64 \
	-fno-exceptions \
	-Wall \
	-O0 \
	-g

# Flags passed to only C files.
CFLAGS_C_Debug := \
	-Wstrict-prototypes

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-fno-threadsafe-statics

INCS_Debug := \
	-Inative_client/src/third_party \
	-I. \
	-I$(obj)/gen

DEFS_Release := \
	'-DNACL_LINUX=1' \
	'-DNACL_ANDROID=0' \
	'-DNACL_OSX=0' \
	'-DNACL_WINDOWS=0' \
	'-D_BSD_SOURCE=1' \
	'-D_POSIX_C_SOURCE=199506' \
	'-D_XOPEN_SOURCE=600' \
	'-D_GNU_SOURCE=1' \
	'-D__STDC_LIMIT_MACROS=1' \
	'-D__STDC_FORMAT_MACROS' \
	'-DNACL_TARGET_SUBARCH=64' \
	'-DNACL_TARGET_ARCH=x86' \
	'-DNACL_BUILD_SUBARCH=64' \
	'-DNACL_BUILD_ARCH=x86' \
	'-DNDEBUG'

# Flags passed to all source files.
CFLAGS_Release := \
	-Werror \
	-pthread \
	-fno-exceptions \
	-Wall \
	-fPIC \
	-Wextra \
	-Wno-long-long \
	-Wswitch-enum \
	-Wsign-compare \
	-Wundef \
	-fdiagnostics-show-option \
	-m64 \
	-fno-exceptions \
	-Wall \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Release := \
	-Wstrict-prototypes

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-fno-threadsafe-statics

INCS_Release := \
	-Inative_client/src/third_party \
	-I. \
	-I$(obj)/gen

OBJS := \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/dyn_array.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/elf_util.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/load_file.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/nacl_all_modules.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/nacl_app_thread.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/nacl_bootstrap_channel_error_reporter.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/nacl_copy.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/nacl_desc_effector_ldr.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/nacl_desc_postmessage.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/nacl_error_gio.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/nacl_error_log_hook.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/nacl_globals.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/nacl_kernel_service.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/nacl_resource.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/nacl_reverse_quota_interface.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/nacl_secure_service.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/nacl_signal_common.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/nacl_stack_safety.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/nacl_syscall_common.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/nacl_syscall_hook.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/nacl_text.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/nacl_valgrind_hooks.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/name_service/default_name_service.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/name_service/name_service.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/sel_addrspace.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/sel_ldr.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/sel_ldr_standard.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/sel_ldr_thread_interface.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/sel_main_chrome.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/sel_mem.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/sel_qualify.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/sel_validate_image.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/thread_suspension_common.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/thread_suspension_unwind.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/linux/nacl_bootstrap_args.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/linux/nacl_thread_nice.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/linux/r_debug.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/linux/reserved_at_zero.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/linux/thread_suspension.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/posix/addrspace_teardown.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/posix/sel_memory.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/linux/x86/nacl_ldt.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/posix/x86/sel_segments.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/posix/nacl_signal.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/posix/sel_addrspace_posix.o \
	$(obj).target/$(TARGET)/native_client/src/trusted/service_runtime/generic/vm_hole.o \
	$(obj).$(TOOLSET)/$(TARGET)/geni/nacl_syscall_handlers.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/native_client/src/trusted/validator/x86/64/libncvalidate_x86_64.a

# Make sure our actions/rules run before any of us.
$(OBJS): | $(action_native_client_src_trusted_service_runtime_service_runtime_gyp_sel_target_nacl_syscall_handler_outputs)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# End of this set of suffix rules
### Rules for final target.
# Build our special outputs first.
$(obj).target/native_client/src/trusted/service_runtime/libsel.a: | $(action_native_client_src_trusted_service_runtime_service_runtime_gyp_sel_target_nacl_syscall_handler_outputs)

# Preserve order dependency of special output on deps.
$(action_native_client_src_trusted_service_runtime_service_runtime_gyp_sel_target_nacl_syscall_handler_outputs): | $(obj).target/native_client/src/trusted/validator/x86/64/libncvalidate_x86_64.a

LDFLAGS_Debug := \
	-pthread \
	-Wl,-z,noexecstack \
	-m64 \
	-rdynamic

LDFLAGS_Release := \
	-pthread \
	-Wl,-z,noexecstack \
	-m64

LIBS :=

$(obj).target/native_client/src/trusted/service_runtime/libsel.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/native_client/src/trusted/service_runtime/libsel.a: LIBS := $(LIBS)
$(obj).target/native_client/src/trusted/service_runtime/libsel.a: TOOLSET := $(TOOLSET)
$(obj).target/native_client/src/trusted/service_runtime/libsel.a: $(OBJS) $(obj).target/native_client/src/trusted/validator/x86/64/libncvalidate_x86_64.a FORCE_DO_CMD
	$(call do_cmd,alink_thin)

all_deps += $(obj).target/native_client/src/trusted/service_runtime/libsel.a
# Add target alias
.PHONY: sel
sel: $(obj).target/native_client/src/trusted/service_runtime/libsel.a

# Add target alias to "all" target.
.PHONY: all
all: sel

