# This file is generated by gyp; do not edit.

export builddir_name ?= ./native_client/src/trusted/service_runtime/out
.PHONY: all
all:
	$(MAKE) -C ../../../.. nacl_error_code env_cleanser sel sel_main_chrome sel_main sel_ldr
