# This file is generated by gyp; do not edit.

export builddir_name ?= ./native_client/src/trusted/service_runtime/linux/out
.PHONY: all
all:
	$(MAKE) -C ../../../../.. nacl_bootstrap_lib nacl_bootstrap_raw nacl_bootstrap_munge_phdr nacl_helper_bootstrap
