# This file is generated by gyp; do not edit.

export builddir_name ?= ./native_client/src/trusted/validator/x86/ncval_seg_sfi/out
.PHONY: all
all:
	$(MAKE) -C ../../../../../.. ncdis_seg_sfi_x86_64 ncval_seg_sfi_x86_64 ncdis_seg_sfi_verbose_x86_64
