# This file is generated by gyp; do not edit.

export builddir_name ?= ./native_client/src/trusted/service_runtime/arch/x86_64/out
.PHONY: all
all:
	$(MAKE) -C ../../../../../.. service_runtime_x86_64
