# This file is generated by gyp; do not edit.

export builddir_name ?= ./native_client/src/trusted/validator/x86/decoder/out
.PHONY: all
all:
	$(MAKE) -C ../../../../../.. nc_opcode_modeling_x86_64 nc_decoder_x86_64 nc_opcode_modeling_verbose_x86_64
