# This file is generated by gyp; do not edit.

export builddir_name ?= ./native_client/src/trusted/validator/x86/ncval_reg_sfi/out
.PHONY: all
all:
	$(MAKE) -C ../../../../../.. ncval_reg_sfi_x86_64 ncval_reg_sfi_verbose_x86_64
