# This file is generated by gyp; do not edit.

export builddir_name ?= ./native_client/src/trusted/validator/x86/out
.PHONY: all
all:
	$(MAKE) -C ../../../../.. ncval_base_x86_64 ncval_base_verbose_x86_64
